### ISSUE TITLE
function and bind

### ISSUE THREAD

**Issue by lilothar** [electronicarts/EASTL#78] opened 2016-12-19 02:50 UTC
I found it that function and bind are not like std stl yet

**Comment by rparolin** [comment] 2016-12-21 16:57
std::bind has been superseded by lambdas because the core language can implement it better than library.  I'd rather not implement bind unless there is a compelling use-case but AFAIK lambdas can do everything bind can do better.

I assume you are speaking about the deprecation of the std::function constructor overloads that take an allocator.  Given the reported issues, its is still valuable from a games industry perspective to specify an allocator for use when the local buffer optimisation can't be used.  This is a short coming of the new container types introduced in C++17 (optional, any) the standard recommends a local buffer optimisation but when a heap allocation occurs the APIs doesn't provide an allocator to get that memory from.  Its not clear for me what direction EASTL will go in this regard.  For the time being I intend to keep the allocator aware overloads in eastl::function as the allocation control it provides out weights the other problems.

**Comment by rparolin** [comment] 2017-01-03 05:11
I'll close this issue as not enough information has been provided.  In future, please provide an explanation of the issue with a very strong preference to providing a test case that proves the issue has been fixed (it also prevents future regressions).  Thank you.

**Closed by rparolin** 2017-01-03 05:11 UTC
