### ISSUE TITLE
Unable to override EA_WCHAR_UNIQUE define inside eabase.h

### ISSUE THREAD

**Issue by ItsAllAboutTheCode** [electronicarts/EASTL#43] opened 2016-04-09 07:34 UTC
The EA_WCHAR_UNIQUE define which is used to determine if wchar_t is a unique type is always defined in eabase.h even if it has already defined by the user
The current code does not check if EA_WCHAR_UNIQUE is defined before defining it.
(https://github.com/electronicarts/EASTL/blob/895afcd5555cb625a86b071078f8f30f16030c36/test/packages/EABase/include/Common/EABase/eabase.h#L695)

Surrounding the block in an `#ifndef EA_WCHAR_UNIQUE` so that the block looks like 

```
#ifndef EA_WCHAR_UNIQUE
    #if EA_CHAR16_NATIVE || EA_CHAR32_NATIVE
        #define EA_WCHAR_UNIQUE 1
    #else
        #define EA_WCHAR_UNIQUE 0
    #endif
#endif
```

 would allow users to override the preprocessor check.

**Comment by rparolin** [comment] 2016-04-13 18:37
// The EA_WCHAR_UNIQUE symbol is defined to 1 if wchar_t is distinct from
// char8_t, char16_t, and char32_t, and defined to 0 if not. In some cases, 
// if the compiler does not support char16_t/char32_t, one of these two types 
// is typically a typedef or define of wchar_t. For compilers that support 
// the C++11 unicode character types often overloads must be provided to 
// support existing code that passes a wide char string to a function that 
// takes a unicode string.

The define is intended to be generated from the inferred compiler context.  Its not meant to be overridden by the user.  Its possible that the logic is incorrect for your compiler/environment but I can't comment on that without more details.

**Comment by DerricMc** [comment] 2016-04-13 20:12
The issue that I am experiencing occurs on the Windows Operating system using Visual Studio 2013 Win64. 

This issue occurs when the Windows std::string is included in any project that uses EASTL. Windows attempts to define two typedefs for specializing std::string on a char16_t and a char32_t when the _CHAR16 macro is defined as 1.

If the _CHAR16T macro defined as 1, "eabase.h" it attempts to typedef char16_t to wchar_t.
The issue that this causes is that if std::string happens to be included before "eabase.h" when Windows attempts to create the two typedefs for std::string<char16_t> and std::string<char32_t> the types are not defined because we told <yvals.h> that we would define them. I believe this issue will be hard to solve as it requires "eabase.h" be included anytime before <string> occurs and my project is using other third party libraries such as gtest and libjsoncpp which includes std::string, but have no knowledge of EASTL.

To workaround this issue I kept _CHAR16T undefined which allows windows <yvals.h>to define char16_t and char32_t to unsigned short. This cause a compiler error inside [eabase.h"](https://github.com/electronicarts/EASTL/blob/master/test/packages/EABase/include/Common/EABase/eabase.h#L724) due to it attempting to typdef char16_t as a wchar_t after it has already been typedef to an unsigned short.

To prevent "eabase.h" from redefining char16_t inside the #ifndef CHAR8_T_DEFINED block 
I defined these three macros inside
```
EA_CHAR16_NATIVE=0
EA_CHAR32_NATIVE=0
CHAR8_T_DEFINED=1
```
This causes "eabase.h" to EA_WCHAR_UNIQUE to be set to 0 which is incorrect because it is a unique type, but char16_t and char32_t are not. 
With these defines the EASTL "string.h" fails to compile because it cannot find a definition for `CharStrlen(const wchar_t* p)` as it is hidden behind the EA_WCHAR_UNIQUE macro.

Since EA_WCHAR_UNIQUE macro cannot be overridden I am unable to compile without modifying eabase.h.

**Comment by gjaegy** [comment] 2017-03-14 15:28
Hi, same issue here with Visual Studio 2013, preventing me from compiling assert/string/thread_support CPP files.
Any idea why the issue status has been set to "wontfix" ?
Thanks !

**Comment by gjaegy** [comment] 2017-06-08 10:23
this issue is quite annyoing :/

each time I update EASTL I have to modify :
- eabase.h
replace
`#if !defined(_HAS_CHAR16_T_LANGUAGE_SUPPORT) || !_HAS_CHAR16_T_LANGUAGE_SUPPORT`
with
`#if (!defined(_HAS_CHAR16_T_LANGUAGE_SUPPORT) || !_HAS_CHAR16_T_LANGUAGE_SUPPORT) && !defined(_CHAR16T)`

- string.h
comment the following method:
`template <typename T, typename Allocator>
basic_string<T, Allocator>::basic_string(CtorSprintf /*unused*/, const value_type* pFormat, ...)`

Is there really no way of avoiding this (MSVC 2013 64) ?

Cheers
Greg

**Comment by rparolin** [comment] 2017-06-08 14:53
Is this only a problem on MSVC2013?  We are going to be deprecating official support for VS2013 next month for internal technology.  That means we won't remove the VS2013 code paths, but we won't be testing it internal anymore and I'll turn off the CI testing on Github.  If its specific to that version of the compiler, I'd prefer to not fix it (as far as I understand it) its to support an interop use-case which EASTL doesn't support.  ie.  eabase.h is required to be the first header included.

**Comment by gjaegy** [comment] 2017-06-09 06:40
Hi Rob,

we are facing this issue with MSVC2013 and the original poster as well (and both when compiling to a 64-bits target). 
So, I can't guarantee it occurs with MSVC2013 only, but it is always reproducible using that compiler I assume.

We are stuck with VS2013 since we are waiting for NSight to support VS2017 :/

**Comment by rparolin** [comment] 2018-10-25 19:55
Is this still an issue? I'd like to close this.

**Closed** 2018-10-26 02:00 UTC
Labels: bug, wontfix
