### ISSUE TITLE
hash_map fails assertion when its destructor is called

### ISSUE THREAD

**Issue by borso** [electronicarts/EASTL#91] opened 2017-02-16 12:40 UTC
Tried to use a hash_map<int,int>.

When it moves out of scope, it fails in its destructor while trying to free the hashmap buckets.
Am I doing something wrong?

**Platform**: Win7, VS2015, x64
**Expression**: _CrtIsValidHeapPointer(block)

**Call Stack:**

> delete_scalar.cpp: operator delete(void * block)
> delete_array.cpp: operator delete[](void * block)
> eastl::allocator::deallocate(void * p, unsigned __int64 __formal) Line 30
> eastl::hashtable<int,eastl::pair<int const ,int>,eastl::allocator,eastl::use_first<eastl::pair<int const ,int> >,eastl::equal_to<int>,eastl::hash<int>,eastl::mod_range_hashing,eastl::default_ranged_hash,eastl::prime_rehash_policy,0,1,1>::DoFreeBuckets(eastl::hash_node<eastl::pair<int const ,int>,0> * * pBucketArray, unsigned __int64 n) Line 1525
> eastl::hashtable<int,eastl::pair<int const ,int>,eastl::allocator,eastl::use_first<eastl::pair<int const ,int> >,eastl::equal_to<int>,eastl::hash<int>,eastl::mod_range_hashing,eastl::default_ranged_hash,eastl::prime_rehash_policy,0,1,1>::~hashtable<int,eastl::pair<int const ,int>,eastl::allocator,eastl::use_first<eastl::pair<int const ,int> >,eastl::equal_to<int>,eastl::hash<int>,eastl::mod_range_hashing,eastl::default_ranged_hash,eastl::prime_rehash_policy,0,1,1>() Line 1438

**Comment by rparolin** [comment] 2017-02-16 17:26
Can you provide a code snippet or a test-case that fails?

**Comment by borso** [comment] 2017-02-17 12:14
This simple test program fails for me.

#include <EASTL/hash_map.h>
eastl::hash_map<int, int> map;

int main()
{
	map[1] = 1;
	return 0;
}

**Comment by rparolin** [comment] 2017-02-18 05:04
Its a static init order problem, I suspect.  EASTL has the requirement to provide a set of custom operator new overloads that allows additional debug information to be passed to the allocator.  Info like an allocation name, etc.

EASTL unit tests provide a default implementation which uses our "general allocator" interface.   We use a static instance of the global of the general allocator.  So I suspect the problem is the compiler picked a static init order of "hash_map" first which tries to allocate memory from our allocator instance which hasn't been initialized yet.

I'm guessing that its 'static init order' because the commit you made to your fork of EASTL marked eastl::hash_map as static but it was omitted from the snippet above.

**Comment by rparolin** [comment] 2017-02-28 07:11
FYI, I'm going to close this issue as invalid unless you have additional information.

**Closed** 2017-03-01 05:57 UTC
