### ISSUE TITLE
eabase.h: error C2371: 'char16_t' : redefinition; different basic types

### ISSUE THREAD

**Issue by Ono-Sendai** [electronicarts/EASTL#12] opened 2016-02-11 01:19 UTC
Hi, I'm getting the compile error below.

I added the following include paths:
D:\programming\EASTL-master\test\packages\EABase\include\Common
D:\programming\EASTL-master\include

and this line:
#include < EASTL/sort.h >

and got:

1>D:\programming\EASTL-master\test\packages\EABase\include\Common\EABase/eabase.h(724): error C2371: 'char16_t' : redefinition; different basic types
1>          C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\yvals.h(528) : see declaration of 'char16_t'

Visual studio 2012, x64 build.

**Comment by rparolin** [comment] 2016-02-11 02:37
I've reproduced this locally.  I'll take a look.

**Comment by c6burns** [comment] 2016-02-11 10:57
This seems to stem from char16_t and char32_t being simply typedefs in VS 12.0 (thus affecting VS2012 and 2013). Therefore _HAS_CHAR16_T_LANGUAGE_SUPPORT is 0, but it is typedef'd and _CHAR16T is defined for us. Switching eabase.h like so resolved the issue for me in VS2013:
```
			#if (!defined(_HAS_CHAR16_T_LANGUAGE_SUPPORT) || !_HAS_CHAR16_T_LANGUAGE_SUPPORT) && !defined(_CHAR16T)
				typedef wchar_t  char16_t;
				typedef uint32_t char32_t;
			#endif
```

**Comment by Ono-Sendai** [comment] 2016-02-11 12:50
Another way to solve the problem is to use the same typedef as MS does in yvals.h:

typedef unsigned short  char16_t

**Comment by danbolt** [comment] 2016-02-12 00:17
This seem to be the same sort of build bug as issue #3.

**Comment by c6burns** [comment] 2016-02-12 01:19
They "seem" the same, but they do not stem from exactly the same code and the resolution of the issues will likely not be the same

**Comment by Jasper-Bekkers** [comment] 2016-02-12 14:41
@c6burns I made the following change locally:

`			#if !defined(_HAS_CHAR16_T_LANGUAGE_SUPPORT) || !_HAS_CHAR16_T_LANGUAGE_SUPPORT && !defined(_CHAR16T)
				typedef wchar_t  char16_t;
				typedef uint32_t char32_t;
			#endif
			#if !defined(_CHAR16T)
				#define _CHAR16T
			#endif
`

Eg. I moved the `#if !defined(_CHAR16T)` below also, because otherwise the typedefs should just be omitted entirely. (since _CHAR16T would always be defined).

**Comment by rparolin** [comment] 2016-02-13 16:31
Is this resolved?  Just confirming before I close.

**Comment by Ono-Sendai** [comment] 2016-02-13 19:06
I'm not sure, has anyone commited a fix?

**Comment by SneWs** [comment] 2016-02-14 00:59
No fix has been committed from what I can see, and I can still repro the issue after a fresh sync using VS2015.

I would suggest that @Jasper-Bekkers creates a PR from his comment since it solves the issue.

**Comment by c6burns** [comment] 2016-02-14 01:46
OK PR is in ... I didn't put this in earlier because it breaks a number of the tests, but that can be handled as a separate issue

**Comment by c6burns** [comment] 2016-02-15 01:39
OK investigating this library in more depth, I don't like this "fix" at all. Some additional changes to EABase are required to properly detect the compiler features and set appropriate defines, such as EA_WCHAR_UNIQUE and others. This will ensure we don't break 1/2 the string tests just to get the library to compile. In the case where people are actually using wchar strings, they will need all this working. This is my first experience with EABase - I'm used to a configure stage determining compiler features for me - but it's fairly logically laid out and commented so I'll take a look through and see what I can come up with

**Comment by rparolin** [comment] 2016-02-15 01:46
@c6burns Agreed.  I actually have a fix for this coming, I wanted to run it against CI before submitting.  Here is a patch file if you want to try it out.

**Comment by rparolin** [comment] 2016-02-15 01:51
[0001-vs2012-fixes.zip](https://github.com/electronicarts/EASTL/files/130022/0001-vs2012-fixes.zip)

**Comment by c6burns** [comment] 2016-02-15 02:13
One issue with the patch is you are using:
`#if defined(EA_WHATEVER)`
But EABase sets a lot of defines to 0, so you need:
`#if defined(EA_WHATEVER) && EA_WHATEVER`

This creates an issue in EASprintf.cpp where a section you intend to be excluded by the preprocessor is still being compiled. Otherwise, success :)

**Comment by rparolin** [comment] 2016-02-16 06:15
Should be fixed now. :)

**Closed by rparolin** 2016-02-16 06:15 UTC

**Comment by SpAMCAN** [comment] 2016-07-05 08:36
I seem to get this bug again in VS2013, exact same error, using a new pull from git (building as win32). I'm new to this, so not sure if it's just something I've set up incorrectly or a bug that's reared its head again.

```
1>d:\users\spam_can\repositories\tremor-engine\src\include\eabase\eabase.h(724): error C2371: 'char16_t' : redefinition; different basic types
1>          c:\program files (x86)\microsoft visual studio 12.0\vc\include\yvals.h(605) : see declaration of 'char16_t'
```
