### ISSUE TITLE
eastl::is_trivially_copyable is not consistent with std::is_trivially_copyable

### ISSUE THREAD

**Issue by lightyang** [electronicarts/EASTL#147] opened 2018-03-07 06:40 UTC
Say we have this class Foo
```cpp
struct Foo {
  int a;

  Foo(int i) : a(i) {
  }
  Foo(Foo &&other) : a(other.a) {
    other.a = 0;
  }
};
```
`std::is_trivially_copyable<Foo>{}` is false while `eastl::is_trivially_copyable<Foo>{}` is true.

**Comment by theryee** [comment] 2018-03-07 07:45
Interesting, looks like this reproduces in gcc but not in clang.

https://travis-ci.org/theryee/EASTL/builds/350190885?utm_source=github_status&utm_medium=notification

**Comment by lightyang** [comment] 2018-03-08 02:37
I guess the gcc behavior is more standard-conformant, assuming the following references are correct: 
http://en.cppreference.com/w/cpp/concept/TriviallyCopyable
http://en.cppreference.com/w/cpp/language/move_constructor#Trivial_move_constructor

`eastl::is_trivially_copyable` is used by `eastl::vector` to determine if it can use memmove to move values, so this issue may lead to some weird problems, say, when you put `Foo`s in an `eastl::vector` and instead of a simple int, `a` is a pointer owned by `Foo`

**Comment by theryee** [comment] 2018-03-09 04:50
I think gcc is incorrect in this case... the class is not trivially copyable because the move constructor is user-defined (and as such is non-trivial copyable move constructor).

**Comment by lightyang** [comment] 2018-03-12 08:49
Ya, I thought you meant gcc and clang gives different outputs for `std::is_trivially_copyable<Foo>`.
The cause of this issue is that EASTL uses `__has_trivial_copy` to implement `is_trivially_copyable`, which don't share the same requirements.

**Comment by rparolin** [comment] 2018-03-28 18:13
__is_trivially_copyable isn't being used on GCC so we would have update the conditional to enable that code path for the version of GCC that implemented that compiler trait.

**Comment by rparolin** [comment] 2018-03-28 19:02
I have a fix and it will be released in the next version of EASTL.

**Closed** 2018-03-28 19:02 UTC
